Schedule = new Mongo.Collection('schedule')
Score = new Mongo.Collection('score')
Commit = new Mongo.Collection('commit')
Lecture = new Mongo.Collection('lecture')
Activity = new Mongo.Collection('activity')
